import re
import sublime, sublime_plugin

currentView = None

class Unity3DTopLevelComplete(sublime_plugin.EventListener):
	
	def on_query_completions(self, view, prefix, locations):
		if not view.file_name().endswith('.cs'):
			return []

		global currentView 
		currentView = view
		result = []

		#UnityEngine
		
		if find('AOT'): result.extend(AOT)

		if find('UnityEngine'):
			result.extend(UNITYENGINE)

			if find('UnityEngine.Flash'): result.extend(UNITYENGINE_FLASH)

			if find('UnityEngine.Serialization'): result.extend(UNITYENGINE_SERIALIZATION)

			if find('UnityEngine.SocialPlatforms'):
				result.extend(UNITYENGINE_SOCIALPLATFORMS)

				if find('UnityEngine.SocialPlatforms.Gamecenter'): result.extend(UNITYENGINE_SOCIALPLATFORMS_GAMECENTER)

				if find('UnityEngine.SocialPlatforms.Impl'): result.extend(UNITYENGINE_SOCIALPLATFORMS_IMPLE)

		if find('UnityEngineInternal'): result.extend(UNITYENGINEINTERNAL)


		#UnityEditor

		if find('TreeEditor'): result.extend(TREEEDITOR)

		if find('UnityEditor'):	
			result.extend(UNITYEDITOR)

			if find('UnityEditor.Callbacks'): result.extend(UNITYEDITOR_CALLBACKS)
	
			if find('UnityEditor.Macros'): result.extend(UNITYEDITOR_MACROS)
	
			if find('UnityEditor.VisualStudioIntegration'): result.extend(UNITYEDITOR_VISUALSTUDIOINTEGRATION)
	
		if find('UnityEditorInternal'):	result.extend(UNITYEDITORINTERNAL)
		
		return completions(result)

def convert (word):
	return 'using[\s]*'+ word +';'

def find (word):
	return currentView.find(convert(word), 0)

def create(word):
	return (word, re.sub('Attribute', '' ,word, 0))

def completions (keys):
	result = []
	
	for word in keys:
		result.append(create(word))
	
	return result

UNITYENGINE = [
'ADBannerView',
'ADError',
'ADInterstitialAd',
'AccelerationEvent',
'AndroidInput',
'AndroidJNIHelper',
'AndroidJNI',
'AndroidJavaObject',
'AndroidJavaClass',
'AnimationClip',
'AnimationCurve',
'AnimationEvent',
'AnimationInfo',
'AnimationState',
'AnimatorStateInfo',
'AnimatorTransitionInfo',
'Application',
'Array',
'AudioSettings',
'BitStream',
'BoneWeight',
'Bounds',
'Caching',
'CharacterInfo',
'ClothSkinningCoefficient',
'Collision',
'Color32',
'Color',
'CombineInstance',
'Compass',
'ComputeBuffer',
'ContactPoint',
'ControllerColliderHit',
'Cursor',
'Debug',
'DetailPrototype',
'Event',
'GL',
'GUIContent',
'GUILayoutOption',
'GUILayoutUtility',
'GUILayout',
'GUISettings',
'GUIStyleState',
'GUIStyle',
'GUIUtility',
'GUI',
'GeometryUtility',
'Gizmos',
'GradientAlphaKey',
'GradientColorKey',
'Gradient',
'Graphics',
'Gyroscope',
'Handheld',
'Hashtable',
'HostData',
'Input',
'JointDrive',
'JointLimits',
'JointMotor',
'JointSpring',
'Keyframe',
'LOD',
'LayerMask',
'LightmapData',
'LightmapSettings',
'LocalNotification',
'LocationInfo',
'LocationService',
'MasterServer',
'MatchTargetWeightMask',
'MaterialPropertyBlock',
'Mathf',
'Matrix4x4',
'Microphone',
'NavMeshHit',
'NavMeshPath',
'NetworkMessageInfo',
'NetworkPlayer',
'NetworkViewID',
'Network',
'NotificationServices',
'Object',
'AssetBundle',
'AudioClip',
'Avatar',
'Component',
'Behaviour',
'Animation',
'Animator',
'AudioChorusFilter',
'AudioDistortionFilter',
'AudioEchoFilter',
'AudioHighPassFilter',
'AudioListener',
'AudioLowPassFilter',
'AudioReverbFilter',
'AudioReverbZone',
'AudioSource',
'Camera',
'ConstantForce',
'GUIElement',
'GUIText',
'GUITexture',
'GUILayer',
'LensFlare',
'Light',
'MonoBehaviour',
'Terrain',
'NavMeshAgent',
'NavMeshObstacle',
'NetworkView',
'Projector',
'Skybox',
'Cloth',
'InteractiveCloth',
'SkinnedCloth',
'Collider',
'BoxCollider',
'CapsuleCollider',
'CharacterController',
'MeshCollider',
'SphereCollider',
'TerrainCollider',
'WheelCollider',
'Joint',
'CharacterJoint',
'ConfigurableJoint',
'FixedJoint',
'HingeJoint',
'SpringJoint',
'LODGroup',
'LightProbeGroup',
'MeshFilter',
'OcclusionArea',
'OcclusionPortal',
'OffMeshLink',
'ParticleAnimator',
'ParticleEmitter',
'ParticleSystem',
'Renderer',
'ClothRenderer',
'LineRenderer',
'MeshRenderer',
'ParticleRenderer',
'ParticleSystemRenderer',
'SkinnedMeshRenderer',
'TrailRenderer',
'Rigidbody',
'TextMesh',
'Transform',
'Tree',
'ComputeShader',
'Flare',
'Font',
'GameObject',
'LightProbes',
'Material',
'ProceduralMaterial',
'Mesh',
'NavMesh',
'PhysicMaterial',
'QualitySettings',
'RenderSettings',
'ScriptableObject',
'GUISkin',
'Shader',
'TerrainData',
'TextAsset',
'Texture',
'Cubemap',
'MovieTexture',
'RenderTexture',
'Texture2D',
'Texture3D',
'WebCamTexture',
'OffMeshLinkData',
'ParticleSystem.Particle',
'Particle',
'Path',
'Physics',
'Ping',
'Plane',
'PlayerPrefsException',
'PlayerPrefs',
'ProceduralPropertyDescription',
'Profiler',
'Quaternion',
'Random',		
'Ray',
'RaycastHit',
'RectOffset',
'Rect',
'RemoteNotification',
'RenderBuffer',
'Resolution',
'Resources',
'Screen',
'Security',
'SleepTimeout',
'Social',
'SoftJointLimit',
'SplatPrototype',
'StaticBatchingUtility',
'String',
'SystemInfo',
'Time',
'TouchScreenKeyboard',
'Touch',
'TreeInstance',
'TreePrototype',
'Vector2',
'Vector3',
'Vector4',
'WWWForm',
'WWW',
'WebCamDevice',
'WheelFrictionCurve',
'WheelHit',
'YieldInstruction',
'AsyncOperation',
'AssetBundleCreateRequest',
'AssetBundleRequest',
'Coroutine',
'WaitForEndOfFrame',
'WaitForFixedUpdate',
'WaitForSeconds',
'iPhoneInput',
'iPhoneSettings',
'iPhoneUtils',
'iPhone',
# enum
'ADErrorCode',
'ADPosition',
'ADSizeIdentifier',
'AndroidActivityIndicatorStyle',
'AnimationBlendMode',
'AnimationCullingType',
'AnimatorCullingMode',
'AnisotropicFiltering',
'AudioReverbPreset',
'AudioRolloffMode',
'AudioSpeakerMode',
'AudioType',
'AudioVelocityUpdateMode',
'AvatarIKGoal',
'AvatarTarget',
'BlendWeights',
'CalendarIdentifier',
'CalendarUnit',
'CameraClearFlags',
'CollisionDetectionMode',
'CollisionFlags',
'ColorSpace',
'ComputeBufferType',
'ConfigurableJointMotion',
'ConnectionTesterStatus',
'CubemapFace',
'CursorMode',
'DepthTextureMode',
'DetailRenderMode',
'DeviceOrientation',
'DeviceType',
'EventModifiers',
'EventType',
'FFTWindow',
'FilterMode',
'FocusType',
'FogMode',
'FontStyle',
'ForceMode',
'FullScreenMovieControlMode',
'FullScreenMovieScalingMode',
'HideFlags',
'HumanBodyBones',
'IMECompositionMode',
'ImagePosition',
'JointDriveMode',
'JointProjectionMode',
'KeyCode',
'LightRenderMode',
'LightShadows',
'LightType',
'LightmapsMode',
'LocationServiceStatus',
'LogType',
'MasterServerEvent',
'MeshTopology',
'NavMeshPathStatus',
'NetworkConnectionError',
'NetworkDisconnection',
'NetworkLogLevel',
'NetworkPeerType',
'NetworkReachability',
'NetworkStateSynchronization',
'ObstacleAvoidanceType',
'OffMeshLinkType',
'ParticleRenderMode',
'ParticleSystemRenderMode',
'PhysicMaterialCombine',
'PlayMode',
'PrimitiveType',
'ProceduralCacheSize',
'ProceduralLoadingBehavior',
'ProceduralProcessorUsage',
'ProceduralPropertyType',
'QueueMode',
'RPCMode',
'RemoteNotificationType',
'RenderTextureFormat',
'RenderTextureReadWrite',
'RenderingPath',
'RigidbodyConstraints',
'RigidbodyInterpolation',
'RotationDriveMode',
'RuntimePlatform',
'ScaleMode',
'ScreenOrientation',
'SendMessageOptions',
'ShadowProjection',
'SkinQuality',
'Space',
'SystemLanguage',
'TerrainRenderFlags',
'TextAlignment',
'TextAnchor',
'TextClipping',
'TextureCompressionQuality',
'TextureFormat',
'TextureWrapMode',
'ThreadPriority',
'TimeScope',
'TouchPhase',
'TouchScreenKeyboardType',
'TransparencySortMode',
'UserAuthorization',
'UserScope',
'UserState',
'WiiUtils.LoadingScreen.Placement',
'WrapMode',
'iOSActivityIndicatorStyle',
'iPhoneGeneration'
]

AOT = [
'MonoPInvokeCallbackAttribute'
]
UNITYENGINE_FLASH = [
'ActionScript',
'FlashPlayer',
]
UNITYENGINE_SERIALIZATION = [
'UnitySurrogateSelector'
]
UNITYENGINE_SOCIALPLATFORMS = [
'IAchievementDescription',
'IAchievement',
'ILeaderboard',
'IScore',
'ISocialPlatform',
'IUserProfile',
'ILocalUser',
'Local',
'Range',
# enum
'TimeScope',
'UserScope', 'UserScope',
'UserState', 'UserState'
]
UNITYENGINE_SOCIALPLATFORMS_GAMECENTER = [
'GameCenterPlatform'
]
UNITYENGINE_SOCIALPLATFORMS_IMPLE = [
'AchievementDescription',
'Achievement',
'Leaderboard',
'Score',
'UserProfile',
'LocalUser',
]
UNITYENGINEINTERNAL = [
'Reproduction',
'TypeInferenceRuleAttribute',
# enum
'TypeInferenceRules'
]

UNITYEDITOR = [
'AnimationClipCurveData',
'AnimationUtility',
'ArrayUtility',
'AssetDatabase',
'AssetImporter',
'AudioImporter',
'ModelImporter',
'MonoImporter',
'MovieImporter',
'SubstanceImporter',
'TextureImporter',
'TrueTypeFontImporter',
'AssetModificationProcessor',
'AssetPostprocessor',
'AssetPreview',
'AssetStoreToolUtils',
'AssetStore',
'BuildPipeline',
'DragAndDrop',
'EditorApplication',
'EditorBuildSettings',
'EditorGUILayout',
'EditorGUIUtility',
'EditorGUI',
'EditorPrefs',
'EditorStyles',
'EditorUserBuildSettings',
'EditorUtility',
'EditorWindow',
'ScriptableWizard',
'Editor',
'FileUtil',
'GameObjectUtility',
'GenericMenu',
'HandleUtility',
'Handles',
'Help',
'LODUtility',
'LightmapEditorSettings',
'Lightmapping',
'MenuCommand',
'MeshUtility',
'ModelImporterClipAnimation',
'MonoScript',
'NavMeshBuilder',
'ObjectNames',
'PlayerSettings.Android',
'PlayerSettings.Wii',
'PlayerSettings.iOS',
'PlayerSettings',
'PrefabUtility',
'ProceduralTexture',
'PropertyDrawer',
'PropertyModification',
'Selection',
'SerializedObject',
'SerializedProperty',
'StaticOcclusionCullingVisualization',
'StaticOcclusionCulling',
'SubstanceArchive',
'TextureImporterSettings',
'Tools',
'Undo',
'UnwrapParam',
'Unwrapping',
# enum
'AndroidBuildSubtarget',
'AndroidPreferredInstallLocation',
'AndroidSdkVersions',
'AndroidShowActivityIndicatorOnLoading',
'AndroidSplashScreenScale',
'AndroidTargetDevice',
'ApiCompatibilityLevel',
'AspectRatio',
'AssetDeleteResult',
'AssetMoveResult',
'AudioImporterFormat',
'AudioImporterLoadType',
'BuildAssetBundleOptions',
'BuildOptions',
'BuildTargetGroup',
'BuildTarget',
'DragAndDropVisualMode',
'DrawCameraMode',
'EditorSkin',
'ExportPackageOptions',
'FlashBuildSubtarget',
'FontRenderingMode',
'FontTextureCase',
'GizmoType',
'ImportAssetOptions',
'InspectorMode',
'LightmapBakeQuality',
'MacFullscreenMode',
'MessageType',
'ModelImporterAnimationCompression',
'ModelImporterAnimationType',
'ModelImporterGenerateAnimations',
'ModelImporterMaterialName',
'ModelImporterMaterialSearch',
'ModelImporterMeshCompression',
'ModelImporterTangentSpaceMode',
'MouseCursor',
'PS3BuildSubtarget',
'PivotMode',
'PivotRotation',
'PrefabType',
'ProceduralOutputType',
'RemoveAssetOptions',
'ReplacePrefabOptions',
'ResolutionDialogSetting',
'ScriptCallOptimizationLevel',
'SelectionMode',
'SerializedPropertyType',
'StaticEditorFlags',
'StaticOcclusionCullingMode',
'StrippingLevel',
'TargetGlesGraphics',
'TextureImporterFormat',
'TextureImporterGenerateCubemap',
'TextureImporterMipFilter',
'TextureImporterNPOTScale',
'TextureImporterNormalFilter',
'TextureImporterType',
'Tool',
'UIOrientation',
'ViewTool',
'WiiBuildDebugLevel',
'WiiBuildSubtarget',
'WiiHio2Usage',
'WiiMemoryArea',
'WiiMemoryLabel',
'WiiRegion',
'XboxBuildSubtarget',
'XboxRunMethod',
'iOSSdkVersion',
'iOSShowActivityIndicatorOnLoading',
'iOSStatusBarStyle',
'iOSTargetDevice',
'iOSTargetOSVersion',
'iOSTargetResolution'
]

TREEEDITOR = [
'FractalNoise',
'Parlin',
'RingLoop',
'SmoothRandom',
'SplineNode',
'TextureAtlas',
'TreeAOSphere',
'TreeAttribute',
'TreeData',
'TreeEditorHelper',
'TreeGroup',
'TreeGroupBranch',
'TreeGroupLeaf',
'TreeGroupRoot',
'TreeMaterial',
'TreeNode',
'TreeSpline',
'TreeTriangle',
'TreeVertex'
]

UNITYEDITOR_CALLBACKS = [
'PostProcessBuildAttribute',
'PostProcessSceneAttribute'
]

UNITYEDITOR_MACROS = [
'MacroEvaluator',
'MethodEvaluator'
]

UNITYEDITOR_VISUALSTUDIOINTEGRATION = [
'SolutionGuidGenerator'
]

UNITYEDITORINTERNAL = [
'AnimationController',
'AssetStore',
'AssetStoreToolUtils',
'AvatorBodyMask',
'AvatorSkeletonMask',
'BlendTree',
'InternalEditorUtility',
'InternalGraphUtility',
'MacroEvents',
'Macros',
'MacroWindow',
'MonoScripts',
'ProfilerDriver',
'ProfilerProperty',
'State',
'StateMachine',
'Transition',
# enum
'AnimatorControllerEventType',
'AnimatorLayerBlendingMode',
'ProfilerArea',
'ProfilerColumn',
'ProfilerViewType',
'TransitionConditionMode'
]