import re
import sublime, sublime_plugin

currentView = None

class Unity3DTopLevelComplete(sublime_plugin.EventListener):
	
	def on_query_completions(self, view, prefix, locations):
		
		if not view.file_name().endswith('.cs'):
			return []
		
		if '.' in view.substr(view.line(view.sel()[0])):
			return []
		
		global currentView

		currentView = view
		result = []

		#UnityEngine
		
		if find('AOT'): result.extend(AOT)

		if find('UnityEngineInternal'): result.extend(UNITYENGINEINTERNAL)

		if find('UnityEngine'):
			result.extend(UNITYENGINE)

			if find('UnityEngine.Flash'): result.extend(UNITYENGINE_FLASH)

			if find('UnityEngine.Serialization'): result.extend(UNITYENGINE_SERIALIZATION)

			if find('UnityEngine.SocialPlatforms'):
				result.extend(UNITYENGINE_SOCIALPLATFORMS)

				if find('UnityEngine.SocialPlatforms.GameCenter'): result.extend(UNITYENGINE_SOCIALPLATFORMS_GAMECENTER)

				if find('UnityEngine.SocialPlatforms.Impl'): result.extend(UNITYENGINE_SOCIALPLATFORMS_IMPL)

		


		#UnityEditor

		if find('TreeEditor'): result.extend(TREEEDITOR)
		
		if find('UnityEditorInternal'):	result.extend(UNITYEDITORINTERNAL)

		if find('UnityEditor'):	
			result.extend(UNITYEDITOR)

			if find('UnityEditor.Callbacks'): result.extend(UNITYEDITOR_CALLBACKS)
	
			if find('UnityEditor.Macros'): result.extend(UNITYEDITOR_MACROS)
	
			if find('UnityEditor.VisualStudioIntegration'): result.extend(UNITYEDITOR_VISUALSTUDIOINTEGRATION)
	
		
		
		return completions(result)

def convert (word):
	return 'using[\s]*'+ word +';'

def find (word):
	return currentView.find(convert(word), 0)

def create(word):
	return (word, re.sub('Attribute', '' ,word, 0))

def completions (keys):
	result = []
	
	for word in keys:
		result.append(create(word))
	
	return result


#words====================================

AOT = [
"MonoPInvokeCallbackAttribute"
]

UNITYENGINE = [
"AndroidJavaObject",
"AndroidJavaClass",
"ThreadSafeAttribute",
"ConstructorSafeAttribute",
"ImplementedInActionScriptAttribute",
"Social",
"Security",
"Types",
"StackTraceUtility",
"UnityException",
"MissingComponentException",
"UnassignedReferenceException",
"MissingReferenceException",
"TextEditor",
"TrackedReference",
"WWW",
"WrapMode",
"AnimationEvent",
"AnimationClip",
"Keyframe",
"AnimationCurve",
"PlayMode",
"QueueMode",
"AnimationBlendMode",
"AnimationPlayMode",
"AnimationCullingType",
"Animation",
"AnimationState",
"AvatarTarget",
"AvatarIKGoal",
"AnimationInfo",
"AnimatorCullingMode",
"AnimatorStateInfo",
"AnimatorTransitionInfo",
"MatchTargetWeightMask",
"Animator",
"HumanBodyBones",
"Avatar",
"HideFlags",
"SendMessageOptions",
"PrimitiveType",
"Space",
"LayerMask",
"RuntimePlatform",
"SystemLanguage",
"LogType",
"AudioSpeakerMode",
"AudioSettings",
"AudioType",
"AudioClip",
"AudioVelocityUpdateMode",
"AudioListener",
"Microphone",
"FFTWindow",
"AudioRolloffMode",
"AudioSource",
"AudioReverbPreset",
"AudioReverbZone",
"AudioLowPassFilter",
"AudioHighPassFilter",
"AudioDistortionFilter",
"AudioEchoFilter",
"AudioChorusFilter",
"AudioReverbFilter",
"PlayerPrefs",
"PlayerPrefsException",
"DeviceType",
"SystemInfo",
"WaitForSeconds",
"WaitForFixedUpdate",
"WaitForEndOfFrame",
"Coroutine",
"RequireComponent",
"AddComponentMenu",
"ContextMenu",
"ExecuteInEditMode",
"HideInInspector",
"ScriptableObject",
"Resources",
"AssetBundleCreateRequest",
"AssetBundleRequest",
"AssetBundle",
"SerializePrivateVariables",
"ThreadPriority",
"SerializeField",
"Profiler",
"CursorMode",
"Cursor",
"LightType",
"LightRenderMode",
"LightShadows",
"OcclusionArea",
"OcclusionPortal",
"FogMode",
"RenderSettings",
"QualityLevel",
"ShadowProjection",
"QualitySettings",
"CameraClearFlags",
"DepthTextureMode",
"TexGenMode",
"Shader",
"AnisotropicFiltering",
"BlendWeights",
"FilterMode",
"TextureWrapMode",
"TextureCompressionQuality",
"Texture",
"TextureFormat",
"Texture2D",
"CubemapFace",
"Cubemap",
"Texture3D",
"MeshFilter",
"CombineInstance",
"MeshTopology",
"Mesh",
"BoneWeight",
"SkinQuality",
"SkinnedMeshRenderer",
"Material",
"Flare",
"LensFlare",
"Renderer",
"Projector",
"Skybox",
"TextMesh",
"Particle",
"ParticleEmitter",
"ParticleAnimator",
"TrailRenderer",
"ParticleRenderMode",
"ParticleRenderer",
"LineRenderer",
"MaterialPropertyBlock",
"RenderBuffer",
"Graphics",
"Resolution",
"LightmapData",
"LightmapsMode",
"ColorSpace",
"LightProbes",
"LightmapSettings",
"GeometryUtility",
"ScreenOrientation",
"Screen",
"SleepTimeout",
"RenderTextureFormat",
"RenderTextureReadWrite",
"RenderTexture",
"MovieTexture",
"GL",
"GUIElement",
"GUITexture",
"TextAlignment",
"TextAnchor",
"GUIText",
"CharacterInfo",
"Font",
"GUILayer",
"MeshRenderer",
"StaticBatchingUtility",
"ImageEffectTransformsToLDR",
"ImageEffectOpaque",
"LOD",
"LODGroup",
"GradientColorKey",
"GradientAlphaKey",
"Gradient",
"ScaleMode",
"GUI",
"GUILayout",
"GUILayoutUtility",
"GUILayoutOption",
"ExitGUIException",
"FocusType",
"GUIUtility",
"FullScreenMovieControlMode",
"FullScreenMovieScalingMode",
"iOSActivityIndicatorStyle",
"AndroidActivityIndicatorStyle",
"Handheld",
"TouchScreenKeyboardType",
"TouchScreenKeyboard",
"iPhoneGeneration",
"iPhone",
"GUISettings",
"GUISkin",
"GUIContent",
"GUIStyleState",
"RectOffset",
"FontStyle",
"ImagePosition",
"GUIStyle",
"TextClipping",
"Event",
"KeyCode",
"EventType",
"EventModifiers",
"Gizmos",
"iPhoneTouchPhase",
"iPhoneTouch",
"iPhoneAccelerationEvent",
"iPhoneOrientation",
"iPhoneInput",
"iPhoneScreenOrientation",
"iPhoneSettings",
"iPhoneKeyboardType",
"iPhoneKeyboard",
"iPhoneMovieControlMode",
"iPhoneMovieScalingMode",
"iPhoneNetworkReachability",
"iPhoneUtils",
"ADSizeIdentifier",
"ADPosition",
"ADErrorCode",
"ADError",
"ADBannerView",
"ADInterstitialAd",
"CalendarIdentifier",
"CalendarUnit",
"LocalNotification",
"RemoteNotification",
"RemoteNotificationType",
"NotificationServices",
"LightProbeGroup",
"Vector2",
"Vector3",
"Color",
"Color32",
"Quaternion",
"Rect",
"Matrix4x4",
"Bounds",
"Vector4",
"Ray",
"Plane",
"Mathf",
"RPCMode",
"ConnectionTesterStatus",
"NetworkConnectionError",
"NetworkDisconnection",
"MasterServerEvent",
"NetworkStateSynchronization",
"NetworkPeerType",
"NetworkLogLevel",
"NetworkPlayer",
"NetworkViewID",
"Ping",
"NetworkView",
"Network",
"BitStream",
"RPC",
"HostData",
"MasterServer",
"NetworkMessageInfo",
"ForceMode",
"Physics",
"RigidbodyConstraints",
"Rigidbody",
"RigidbodyInterpolation",
"JointMotor",
"JointSpring",
"JointLimits",
"Joint",
"HingeJoint",
"SpringJoint",
"FixedJoint",
"SoftJointLimit",
"JointDriveMode",
"JointProjectionMode",
"JointDrive",
"CharacterJoint",
"ConfigurableJointMotion",
"RotationDriveMode",
"ConfigurableJoint",
"ConstantForce",
"CollisionDetectionMode",
"Collider",
"BoxCollider",
"SphereCollider",
"MeshCollider",
"CapsuleCollider",
"RaycastCollider",
"WheelFrictionCurve",
"WheelHit",
"WheelCollider",
"RaycastHit",
"PhysicMaterialCombine",
"PhysicMaterial",
"ContactPoint",
"Collision",
"CollisionFlags",
"ControllerColliderHit",
"CharacterController",
"Cloth",
"InteractiveCloth",
"ClothSkinningCoefficient",
"SkinnedCloth",
"ClothRenderer",
"ParticleSystemRenderMode",
"ParticleSystem",
"ParticleSystemRenderer",
"TextAsset",
"ProceduralProcessorUsage",
"ProceduralCacheSize",
"ProceduralLoadingBehavior",
"ProceduralPropertyType",
"ProceduralPropertyDescription",
"ProceduralMaterial",
"TreePrototype",
"DetailRenderMode",
"DetailPrototype",
"SplatPrototype",
"TerrainData",
"TreeInstance",
"TerrainRenderFlags",
"Terrain",
"Tree",
"TerrainCollider",
"WWWForm",
"CacheIndex",
"Caching",
"AsyncOperation",
"NetworkReachability",
"Application",
"UserAuthorization",
"Behaviour",
"RenderingPath",
"TransparencySortMode",
"Camera",
"ComputeShader",
"ComputeBufferType",
"ComputeBuffer",
"Debug",
"NotConvertedAttribute",
"NotFlashValidatedAttribute",
"NotRenamedAttribute",
"MonoBehaviour",
"TouchPhase",
"IMECompositionMode",
"Touch",
"DeviceOrientation",
"AccelerationEvent",
"Gyroscope",
"LocationInfo",
"LocationServiceStatus",
"LocationService",
"Compass",
"Input",
"Object",
"Component",
"Light",
"GameObject",
"Transform",
"Time",
"Random",
"YieldInstruction",
"WebCamFlags",
"WebCamDevice",
"WebCamTexture",
"jvalue",
"AndroidJNIHelper",
"AndroidJNI",
"ObstacleAvoidanceType",
"NavMeshAgent",
"OffMeshLinkType",
"OffMeshLinkData",
"NavMeshHit",
"NavMesh",
"OffMeshLink",
"NavMeshPathStatus",
"NavMeshPath",
"NavMeshObstacle",
"AndroidInput",
"PropertyAttribute",
"RangeAttribute",
"MultilineAttribute",
"Motion",
"AndroidJavaRunnable"
]

UNITYENGINE_FLASH = [
"ActionScript",
"FlashPlayer"
]

UNITYENGINE_SERIALIZATION = [
"UnitySurrogateSelector"
]

UNITYENGINE_SOCIALPLATFORMS = [
"Local",
"ISocialPlatform",
"ILocalUser",
"UserState",
"IUserProfile",
"IAchievement",
"IAchievementDescription",
"IScore",
"UserScope",
"TimeScope",
"Range",
"ILeaderboard"
]

UNITYENGINE_SOCIALPLATFORMS_GAMECENTER = [
"GameCenterPlatform"
]

UNITYENGINE_SOCIALPLATFORMS_IMPL = [
"GameCenterPlatform"
]

UNITYENGINEINTERNAL = [
"TypeInferenceRules",
"TypeInferenceRuleAttribute",
"Reproduction"
]

TREEEDITOR = [
"TreeData",
"TreeEditorHelper",
"SmoothRandom",
"Perlin",
"FractalNoise",
"RingLoop",
"SplineNode",
"TextureAtlas",
"TreeAOSphere",
"TreeAttribute",
"TreeGroup",
"TreeGroupBranch",
"TreeGroupLeaf",
"TreeGroupRoot",
"TreeMaterial",
"TreeNode",
"TreeSpline",
"TreeTriangle",
"TreeVertex"
]

UNITYEDITOR = [
"AssemblyHelper",
"InitializeOnLoadAttribute",
"FileUtil",
"AssetStoreAsset",
"AssemblyTypeInfoGenerator",
"Xcode4Controller",
"Handles",
"EditorGUILayout",
"EditorGUI",
"ListViewState",
"Editor",
"BodyPart",
"BoneState",
"SearchableEditorWindow",
"SearchFilter",
"SceneModeUtility",
"SceneView",
"AndroidSdkRoot",
"MathUtils",
"VCAsset",
"VCAssetList",
"VCChangelist",
"VCChanges",
"VCDatabase",
"VCMessage",
"VCMonitor",
"VCPath",
"CheckoutMode",
"VCProvider",
"VCTask",
"VCListControl",
"VCListItem",
"VCMenuChange",
"VCMenuPending",
"VCMenuProject",
"VCOverlay",
"VCWindowChange",
"VCWindowPending",
"VCWindowRevert",
"AnimationClipCurveData",
"AnimationUtility",
"RemoveAssetOptions",
"ImportAssetOptions",
"AssetDatabase",
"AssetStatus",
"AssetsItem",
"PackageInfo",
"BuildOptions",
"BuildAssetBundleOptions",
"BuildPipeline",
"BuildTarget",
"BuildTargetGroup",
"PostProcessAttribute",
"StaticEditorFlags",
"EditorApplication",
"EditorGUIUtility",
"MessageType",
"EditorSkin",
"MouseCursor",
"DrawCameraMode",
"HandleUtility",
"SerializationMode",
"ExternalVersionControl",
"EditorSettings",
"EditorUserSettings",
"EditorWindow",
"CustomEditor",
"CanEditMultipleObjects",
"ReplacePrefabOptions",
"PrefabType",
"PropertyModification",
"PrefabUtility",
"UndoSnapshot",
"Undo",
"ExportPackageOptions",
"PS3BuildSubtarget",
"WiiBuildSubtarget",
"WiiBuildDebugLevel",
"XboxBuildSubtarget",
"XboxRunMethod",
"AndroidBuildSubtarget",
"FlashBuildSubtarget",
"MetroBuildType",
"EditorBuildSettingsScene",
"EditorBuildSettings",
"EditorUserBuildSettings",
"ActiveEditorTracker",
"InspectorMode",
"HierarchyType",
"HierarchyProperty",
"AssetMoveResult",
"AssetDeleteResult",
"SaveAssetsProcessor",
"MonoImporter",
"ModelImporterClipAnimation",
"ModelImporterGenerateMaterials",
"ModelImporterMaterialName",
"ModelImporterMaterialSearch",
"ModelImporterTangentSpaceMode",
"ModelImporterMeshCompression",
"ModelImporterAnimationCompression",
"ModelImporterGenerateAnimations",
"ModelImporterAnimationType",
"HumanTemplate",
"TakeInfo",
"ModelImporter",
"TextureImporterFormat",
"TextureImporterMipFilter",
"TextureImporterGenerateCubemap",
"TextureImporterNPOTScale",
"TextureImporterNormalFilter",
"TextureImporterType",
"TextureImporter",
"TextureImporterSettings",
"AudioImporterFormat",
"AudioImporterLoadType",
"AudioImporterChannels",
"AudioImporter",
"MovieImporter",
"FontTextureCase",
"FontRenderingMode",
"TrueTypeFontImporter",
"TextureUsageMode",
"MeshUtility",
"ArrayUtility",
"UnwrapParam",
"Unwrapping",
"Lightmapping",
"LightmapBakeQuality",
"LightmapEditorSettings",
"StaticOcclusionCullingMode",
"StaticOcclusionCulling",
"StaticOcclusionCullingVisualization",
"NavMeshBuilder",
"ResolutionDialogSetting",
"AspectRatio",
"MacFullscreenMode",
"StrippingLevel",
"ScriptCallOptimizationLevel",
"iOSSdkVersion",
"iOSTargetOSVersion",
"iOSTargetDevice",
"iOSShowActivityIndicatorOnLoading",
"AndroidTargetDevice",
"AndroidSdkVersions",
"AndroidPreferredInstallLocation",
"AndroidShowActivityIndicatorOnLoading",
"TargetGlesGraphics",
"iOSTargetResolution",
"UIOrientation",
"iOSStatusBarStyle",
"AndroidSplashScreenScale",
"ApiCompatibilityLevel",
"WiiRegion",
"WiiMemoryLabel",
"WiiMemoryArea",
"WiiHio2Usage",
"PlayerSettings",
"PreferenceItem",
"ScriptableWizard",
"SerializedPropertyType",
"SerializedObject",
"SerializedProperty",
"ProceduralOutputType",
"SubstanceImporter",
"SubstanceArchive",
"ProceduralTexture",
"SelectionMode",
"Selection",
"EditorUtility",
"MenuItem",
"MenuCommand",
"GizmoType",
"DrawGizmo",
"EditorPrefs",
"Help",
"ObjectNames",
"DragAndDropVisualMode",
"DragAndDrop",
"UnityStats",
"MonoScript",
"NETVersion",
"Unsupported",
"GameObjectUtility",
"EditorStyles",
"GenericMenu",
"ViewTool",
"PivotMode",
"PivotRotation",
"Tool",
"Tools",
"LODUtility",
"VCConfigField",
"VCPlugin",
"AssetModificationProcessor",
"AssetPostprocessor",
"AssetImporter",
"AssetPreview",
"CustomPropertyDrawer",
"PropertyDrawer"
]

UNITYEDITOR_CALLBACKS = [
"PostProcessBuildAttribute",
"PostProcessSceneAttribute"
]

UNITYEDITOR_MACROS = [
"MacroEvaluator",
"MethodEvaluator"
]

UNITYEDITOR_VISUALSTUDIOINTEGRATION = [
"SolutionGuidGenerator"
]

UNITYEDITORINTERNAL = [
"AssetStoreToolUtils",
"InternalEditorUtility",
"MacroEvents",
"MacroWindow",
"AnimatorController",
"Transition",
"StateMachine",
"MonoScripts",
"AssetStore",
"AvatarBodyMask",
"AvatarSkeletonMask",
"BlendTree",
"InternalGraphUtility",
"Macros",
"ProfilerViewType",
"ProfilerColumn",
"ProfilerArea",
"ProfilerDriver",
"ProfilerProperty",
"TransitionConditionMode",
"State",
"AnimatorControllerEventType",
"AnimatorLayerBlendingMode"
]

#============================words end